name: staging
description: staging

runs:
  using: "composite"

  steps:
    - name: 🏗️ Build Staging App
      shell: bash
      run: |
        cd app
        flutter build apk --target lib/main_staging.dart
