name: bpub

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  meta: ^1.10.0
  supabase: ^2.0.5
  supabase_flutter: ^2.3.0

dev_dependencies:
  bpub_dev:
