name: booksinarow
version: 0.1.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bpub:
  flutter:
    sdk: flutter

dev_dependencies:
  bpub_dev:

flutter:
  uses-material-design: true
  generate: true
