name: booksinarow
version: 0.1.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bpub:
  envied: ^0.5.3
  flutter:
    sdk: flutter

dev_dependencies:
  bpub_dev:
  envied_generator: ^0.5.3

flutter:
  uses-material-design: true
  generate: true
