name: bpub_dev

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  test_beautifier: ^0.1.0+1
  very_good_analysis: ^5.1.0
