name: feature

on:
  pull_request:
    types: [edited, opened, synchronize, reopened]


jobs:
  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    permissions: read-all
    with:
      includes: "**/*.md"
      modified_files_only: true

  build-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DATABASE_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_STAGING_PROJECT_ID }}
      # FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      # FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      # FIREBASE_ANDROID_STAGING_APP_ID: ${{ secrets.FIREBASE_ANDROID_STAGING_APP_ID }}
      # FIREBASE_IOS_STAGING_APP_ID: ${{ secrets.FIREBASE_IOS_STAGING_APP_ID }}
      # GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # RUN_ID: ${{ github.run_id }}
      # SHA: ${{ github.sha }}

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: 🔍️ Run Checks
        uses: ./.github/actions/code-check

      - name: 🚀 Deploy Staging
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: ./.github/actions/staging
