name: main

on:
  push:
    branches:
      - main


jobs:      
  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    permissions: read-all
    with:
      includes: "**/*.md"
      modified_files_only: true

  build-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DATABASE_PASSWORD: ${{ secrets.SUPABASE_DATABASE_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PRODUCTION_PROJECT_ID }}
      # FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      # FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      # FIREBASE_ANDROID_PRODUCTION_APP_ID: ${{ secrets.FIREBASE_ANDROID_PRODUCTION_APP_ID }}
      # FIREBASE_IOS_PRODUCTION_APP_ID: ${{ secrets.FIREBASE_IOS_PRODUCTION_APP_ID }}
      # GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # RUN_ID: ${{ github.run_id }}
      # SHA: ${{ github.sha }}

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: 🔍️ Check Code
        uses: ./.github/actions/code-check
          
      - name: 🚀 Deploy Production
        uses: ./.github/actions/production
